# Generated by Django 6.0 on 2025-12-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
