# Generated by Django 6.0 on 2025-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brend'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=43),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_order',
            field=models.CharField(choices=[('good', 'yaxshi'), ('bed', 'yomod'), ('enough', 'qoniqarli')], default=1, max_length=342),
            preserve_default=False,
        ),
    ]
