# Generated by Django 6.0 on 2025-12-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_name_order_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(choices=[('good', 'yaxshi'), ('bed', 'yomod'), ('enough', 'qoniqarli')], default=1, max_length=342),
            preserve_default=False,
        ),
    ]
